In [11]:
import re
import PyPDF2
import tabula
import pandas as pd
import numpy as np

def inches_to_points(inches):
    return inches * 72

def extract_tables_tabula(doc):
    # Read the PDF file using tabula
    # Convert the coordinates from inches to points
    top, left, bottom, right = inches_to_points(0), inches_to_points(0), inches_to_points(7.75), inches_to_points(11)
    area = [top, left, bottom, right]
    df = tabula.read_pdf(doc, pages='all', multiple_tables=True, stream=True, guess=True, area=area)
    df = pd.concat(df)
    return df
    print(df)

def clear_cells_starting_with_letter(s):
    if isinstance(s, str) and s:
        if s[0].isalpha():
            return ''
        elif len(s) > 1 and s[0] == "'" and not s[1].isdigit():
            return ''
    return s


def extract_number_and_remaining_text(s):
    pattern = r"(\d+\.\d{3})"
    match = re.search(pattern, s)
    if match:
        number = match.group(0)
        remaining_text = re.sub(pattern, '', s)
        return number, remaining_text
    return np.nan, s

def clear_row_with_width_x(row):
    if row["B"] == 'Width   x':
        return pd.Series({key: '' for key in row.index})
    return row

def clear_row_with_width_blank(row):
    if pd.isnull(row["A"]):
        return pd.Series({key: '' for key in row.index})
    return row


def convert_pdf_to_excel(pdf_file):
    # Open the PDF file in binary mode
    with open(pdf_file, "rb") as file:
        # Create a PDF reader object
        reader = PyPDF2.PdfReader(file)
        # Get the number of pages in the PDF file
        num_pages = len(reader.pages)

    # Read the PDF file using tabula
    print('using tabula')
    df = extract_tables_tabula(doc)


    df.to_excel("output2.xlsx", index=False)
    return df


doc = "/home/justin/PycharmProjects/Sheet/AM001440D .pdf"

convert_pdf_to_excel(doc)

using tabula

,Job ID: AM001440D,Unnamed: 0,Part Consolidation Report,Unnamed: 1,Unnamed: 2,Unnamed: 3
0,QTY Part Description Width x,NaN,NaN,Length Material,EVO Barcode SEQ #,NaN
1,PSI ID: 1 - Sample Door & Panels (2),NaN,NaN,NaN,NaN,NaN
2,1 Door- (Sample - Internal use only) 12.000,x,NaN,15.000 WORCPC19.05WORC,*AM001440DDORB0001.DXF_/OAR*,1
3,NaN,NaN,NaN,NaN,AM001440DDORB0001.DXF /AR,NaN
4,Total Parts Per Reports: 1.00,NaN,NaN,NaN,NaN,NaN
5,Parts Requiring Bottom Machining,NaN,NaN,NaN,NaN,NaN
6,PSI Part Description Width,NaN,NaN,Length Material,BottomProgram,SEQ #