In [2]:
import re
import PyPDF2
import tabula
import pandas as pd
import numpy as np

def inches_to_points(inches):
    return inches * 72

def extract_tables_tabula(doc):
    area = [inches_to_points(0), inches_to_points(0), inches_to_points(7.75), inches_to_points(11)]
    df_list = tabula.read_pdf(doc, pages='all', multiple_tables=True, stream=True, guess=True, area=area)
    df = pd.concat(df_list)
    return df

def clear_cells_starting_with_letter(s):
    if isinstance(s, str) and s:
        if s[0].isalpha() or (len(s) > 1 and s[0] == "'" and not s[1].isdigit()):
            return ''
    return s

def extract_number_and_remaining_text(s):
    pattern = r"(\d+\.\d{3})"
    match = re.search(pattern, s)
    if match:
        number = match.group(0)
        remaining_text = re.sub(pattern, '', s)
        return number, remaining_text
    return np.nan, s

def clear_row_with_width_x(row):
    return pd.Series({key: '' for key in row.index}) if row["B"] == 'Width   x' else row

def clear_row_with_width_blank(row):
    return pd.Series({key: '' for key in row.index}) if pd.isnull(row["A"]) else row

def convert_pdf_to_excel(pdf_file):
    with open(pdf_file, "rb") as file:
        num_pages = len(PyPDF2.PdfReader(file).pages)

    print('Using tabula')
    df = extract_tables_tabula(pdf_file)

    df.to_excel("output2.xlsx", index=False)
    return df

doc = "/home/justin/PycharmProjects/Sheet/AM001671.pdf"
convert_pdf_to_excel(doc)

Using tabula

,Job ID: AM001671,Unnamed: 0,Unnamed: 1,Part Consolidation Report,Unnamed: 2,Unnamed: 3
0,QTY Part Description,Width x,NaN,Length Material,EVO Barcode,SEQ #
1,PSI ID: 1 - End (Finishing) Panel -,NaN,NaN,NaN,NaN,NaN
2,1 End (Finishing) Panel - Tall,26.130,x,95.500 L175PC16.26L175,*AM001671PART0014.DXF_/OAR*,122
3,NaN,NaN,NaN,NaN,AM001671PART0014.DXF /AR,NaN
4,PSI ID: 2 - Wall Refrigerator - 2 Do,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
19,1 Base Filler - Dish Washer 3.000,x,30.000 K02(AU)PC16.26K02(AU),NaN,*AM001671PART0003.DXF_/OAR*,170
20,NaN,NaN,NaN,NaN,AM001671PART0003.DXF /AR,NaN
21,Total Parts Per Reports: 216.00,NaN,NaN,NaN,NaN,NaN
22,Parts Requiring Bottom Machining,NaN,NaN,NaN,NaN,NaN
23,PSI Part Description Width,NaN,Length Material,NaN,BottomProgram,SEQ #